import { Attachments } from './user-attachments';
import { Client } from './user-clients';
import { Cv } from './user-cv';
import { EducationInfo } from './user-education-info';
import { Projects } from './user-projects';
import { Roles } from './user-roles';
import { Status } from './user-status';
import { Technology } from './user-technology';
import { workHistoryInfo } from './user-work-history-info';
import { WorkType } from './user-work-type';
import { workHistory } from './work-history';

export interface User {
	id: number;
	email: string;
	password: string;
	name: null | string;
	surname: null | string;
	positionDescription: null | string;
	language: null | string;
	endReason: null | string;
	avatarUrl: null | string;
	phone: null | string;
	city: null | string;
	salary: number;
	address: null | string;
	skills: null | string;
	experience: null | string;
	isBanned: boolean;
	banReason: null | string;
	birthday: null | string;
	cvId: null | number;
	cv: null | Cv;
	startDate: null | string;
	endDate: null | string;
	workType: null | WorkType;
	roles: null | Roles;
	leadingInProjects: Array<Projects>;
	teamSize: string;
	ourCompanyResponsibility: string;
	pricingModel: string;
	averageHoursPerMonth: number;
	hourlyRate: number;
	fixedPrice: number;
	client: Client;
	workHistories: null | workHistory;
	projectDeploymentStatus: 'string';
	projectLink: 'string';
	demoCredentialsLogin: 'string';
	demoCredentialsPassword: 'string';
	mainParticipant: string;
	secondaryParticipants: Array<string>;
	participatingInProjects: Array<Projects>;
	attachedAttachments: Attachments;
	publishedAttachments: Attachments;
	techStack: null | Technology;
	status: Status;
	educationInfo: Array<EducationInfo>;
	upwork: null | string;
	github: null | string;
	linkedin: null | string;
	telegramTag: null | string;
	individualEntrepreneurName: null | string;
	individualEntrepreneurAddress: null | string;
	individualEntrepreneurIndividualTaxNumber: null | number;
	individualEntrepreneurBankAccounNumber: null | string;
	individualEntrepreneurBankName: null | string;
	individualEntrepreneurBankCode: null | number;
	individualEntrepreneurBeneficiaryBank: null | string;
	individualEntrepreneurSwiftCode: null | string;
	workHistory: workHistory;
	defaultCoverLetter: null | string;
	createdAt: string;
	updatedAt: string;
	workHistoryInfoId: number;
	workHistoryInfo: null | workHistoryInfo;
	token: null;
}
